name: isar_community_minimal_test
description: A new Flutter project.
version: 1.0.0+1

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  isar_community:
    path: ../isar_community/packages/isar_community
  isar_community_flutter_libs:
    path: ../isar_community/packages/isar_community_flutter_libs

  faker: ^2.1.0    

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  flutter_lints: ^2.0.0

  isar_community_generator:
    path: ../isar_community/packages/isar_community_generator

flutter:
  uses-material-design: true

dependency_overrides:
  isar_community:
    path: ../isar_community/packages/isar_community
  isar_community_flutter_libs:
    path: ../isar_community/packages/isar_community_flutter_libs
  isar_community_generator:
    path: ../isar_community/packages/isar_community_generator


    